// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var ViewModel;
    ViewModel = {
      tickets: ko.observableArray()
    };
    return async.waterfall([
      function(callback) {
        return $.ajax({
          url: "/node/getuser"
        }).done(function(userdata) {
          if (!userdata) {
            return window.location.replace("/node/google");
          } else {
            return callback(null, userdata);
          }
        });
      }, function(userdata, callback) {
        var usermail;
        usermail = userdata.emails[0].value;
        return socket.emit('getMyTickets', usermail, callback);
      }, function(results, callback) {
        var iterator;
        iterator = function(item, cb) {
          item.value.moment = moment(item.value.modified).fromNow();
          return cb(null, item.value);
        };
        return async.map(results, iterator, callback);
      }, function(tickets, callback) {
        ViewModel.tickets(tickets);
        return ko.applyBindings(ViewModel);
      }
    ]);
  });

}).call(this);
