// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    if (typeof io !== "undefined" && io !== null) {
      window.socket = io.connect(location.host, {
        resource: "node/socket.io"
      });
    } else {
      window.location.replace("/serverdown/");
    }
    socket.on('connect_failed', function() {
      return window.location.replace("/serverdown/");
    });
    socket.on('reconnect_failed', function() {
      return window.location.replace("/serverdown/");
    });
    socket.on('error', function() {
      return window.location.replace("/node/google/");
    });
    return $(document).foundation();
  });

}).call(this);
