// Generated by CoffeeScript 1.6.3
(function() {
  var getUrlVars, vars;

  vars = {};

  getUrlVars = function() {
    return window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/g, function(m, key, value) {
      return vars[key] = value;
    });
  };

  $(document).ready(function() {
    return $.ajax({
      url: "/node/getuser"
    }).done(function(userdata) {
      if (!userdata) {
        return window.location.replace("/node/google");
      } else {
        getUrlVars();
        return alert(vars["id"]);
      }
    });
  });

}).call(this);
