// Generated by CoffeeScript 1.6.3
(function() {
  var getUrlVars, id;

  id = 0;

  getUrlVars = function() {
    var parts, vars;
    vars = {};
    parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/g, function(m, key, value) {
      return vars[key] = value;
    });
    return vars;
  };

  $(document).ready(function() {
    return $.ajax({
      url: "/node/getuser"
    }).done(function(userdata) {
      if (!userdata) {
        return window.location.replace("/node/google");
      } else {
        id = getUrlVars()["id"];
        return alert(id);
      }
    });
  });

}).call(this);
