// Generated by CoffeeScript 1.6.3
(function() {
  var ViewModel, getMessages, getUrlVars, urlvars;

  urlvars = {};

  getUrlVars = function() {
    return window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/g, function(m, key, value) {
      return urlvars[key] = value;
    });
  };

  ViewModel = {
    user: {},
    ticket: ko.observable(),
    messages: ko.observableArray()
  };

  getMessages = function() {
    return socket.emit('getMessages', urlvars.id, function(err, ticket, messages) {
      if (err) {
        return console.log(err);
      } else {
        ViewModel.ticket(ticket);
        console.log(ticket);
        ViewModel.messages(messages);
        return console.log(messages);
      }
    });
  };

  $(document).ready(function() {
    return $.ajax({
      url: "/node/getuser"
    }).done(function(userdata) {
      if (!userdata) {
        return window.location.replace("/node/google");
      } else {
        ViewModel.user = userdata;
        getUrlVars();
        if (urlvars != null ? urlvars.id : void 0) {
          return getMessages();
        }
      }
    });
  });

}).call(this);
